name: QuimpGrp
version: "0.1"
license: "GPL-2.0-or-later"
date: 2021-11-25
description: |
    A database of QUasiprimitive, IMPrimitive permutation groups.

authors:
    - name: Dominik Bernhardt
      url: dominikbernhardt.de

maintainers:
    - name: Dominik Bernhardt
      url: dominikbernhardt.de

GAP: ">= 4.11"

www: https://DominikBernhardt.github.io/QuimpGrp/
readme: README.md
packageinfo: https://DominikBernhardt.github.io/QuimpGrp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/DominikBernhardt/QuimpGrp/releases/download/v0.1/QuimpGrp-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ber21</span>]   <b class='BibAuthor'>Bernhardt, D.</b>,
     <i class='BibTitle'>QuimpGrp, A database of QUasiprimitive, IMPrimitive permutation groups.,
             Version 0.1</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://DominikBernhardt.github.io/QuimpGrp/">https://DominikBernhardt.github.io/QuimpGrp/</a></span>.
    </p>
    

bibtex: |
    @misc{ QuimpGrp0.1,
      author =           {Bernhardt, D.},
      title =            {{QuimpGrp}, A database of QUasiprimitive, IMPrimitive permutation groups., {V}ersion 0.1},
      month =            {Nov},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href           {https://DominikBernhardt.github.io/QuimpGrp/}           {\texttt{https://DominikBernhardt.github.io/}\discretionary
                          {}{}{}\texttt{QuimpGrp/}}},
      printedkey =       {Ber21}
    }

